.screen 64 64

.reg sine r2
.reg cosine r3
.reg center_x r4
.reg center_y r5
.reg palette r6
.reg palette_ticks r7
.reg dx r8
.reg dy r9
.reg rows r10
.reg pixels r11
.reg abs_dx r12
.reg abs_dy r13
.reg color r14
.reg temp r15
.reg dy_positive r16

; Rotating, breathing polar grid.
;
; atan2 is approximated by a 40-sector diamond angle:
;   quarter_angle = 10 * abs(dy) / (abs(dx) + abs(dy))
; Distance is approximated by max(abs(dx), abs(dy)) +
; 3/8 * min(abs(dx), abs(dy)). Radial boundaries retain the source's
; 3.0 initial spacing and 1.08 exponential growth.

start:
  imm sine 0
  imm cosine 1000000
  imm palette 0
  imm palette_ticks 5

frame:
  ; rr = 25 + 5*cos(frame), with the source's negative frame direction.
  muli r0 cosine 5
  divi0 1000000
  addi0 25
  mov temp r0

  ; center_x = 32 + rr*cos(frame)
  mul r0 temp cosine
  divi0 1000000
  addi0 32
  mov center_x r0

  ; center_y = 32 + rr*sin(frame)
  mul r0 temp sine
  divi0 1000000
  addi0 32
  mov center_y r0

  imm r0 0
  sub0 center_y
  mov dy r0
  imm rows 64

row:
  imm r0 0
  sub0 center_x
  mov dx r0
  mov abs_dy dy
  addi r0 abs_dy 1
  jc r0 dy_nonnegative
  neg abs_dy
  imm dy_positive 0
  jmp dy_ready

dy_nonnegative:
  imm dy_positive 1

dy_ready:
  imm pixels 64

pixel:
  mov abs_dx dx

  ; Split by quadrant while converting both deltas to absolute values.
  jc abs_dx dx_positive

  ; dx <= 0. Both sides agree on the y axis; handle the exact center here.
  neg abs_dx
  add temp abs_dx abs_dy
  jc temp dx_nonpositive_noncenter
  imm color 0
  jmp angle_ready

dx_nonpositive_noncenter:
  jc dy_positive quadrant_2

  ; Quadrant 3: sector = 20 + q.
  muli color abs_dy 10
  div r0 color temp
  addi0 20
  mov color r0
  jmp angle_ready

quadrant_2:
  ; Quadrant 2: sector = 20 - q.
  muli color abs_dy 10
  div color color temp
  imm temp 20
  sub color temp color
  jmp angle_ready

dx_positive:
  jc dy_positive quadrant_1

  ; Quadrant 4: sector = 40 - q, with the positive x axis mapped to zero.
  muli color abs_dy 10
  add temp abs_dx abs_dy
  div color color temp
  jc color quadrant_4_nonzero
  imm color 0
  jmp angle_ready

quadrant_4_nonzero:
  imm temp 40
  sub color temp color
  jmp angle_ready

quadrant_1:
  ; Quadrant 1: sector = q. The denominator is positive because dx > 0.
  add temp abs_dx abs_dy
  muli r0 abs_dy 10
  div0 temp
  mov color r0

angle_ready:
  ; Approximate hypot(dx,dy) and scale it by 100 for radial boundaries.
  sub temp abs_dx abs_dy
  jc temp dx_is_larger

  ; dy >= dx
  muli r0 abs_dx 3
  divi0 8
  mov temp r0
  add abs_dx abs_dy temp
  jmp distance_ready

dx_is_larger:
  muli r0 abs_dy 3
  divi0 8
  mov temp r0
  add abs_dx abs_dx temp

distance_ready:
  muli abs_dx abs_dx 100

  ; Classify the approximate distance through the exact cumulative ring
  ; thresholds generated by spacing = floor(spacing * 1.08).
  subi r0 abs_dx 3176
  jc r0 radial_9_16
  subi r0 abs_dx 973
  jc r0 radial_4_8
  subi r0 abs_dx 300
  jc r0 radial_2_3
  subi r0 abs_dx 0
  jc r0 radial_1
  imm r0 0
  jmp radial_ready

radial_1:
  imm r0 1
  jmp radial_ready

radial_2_3:
  subi r0 abs_dx 624
  jc r0 radial_3
  imm r0 2
  jmp radial_ready

radial_3:
  imm r0 3
  jmp radial_ready

radial_4_8:
  subi r0 abs_dx 1755
  jc r0 radial_6_8
  subi r0 abs_dx 1349
  jc r0 radial_5
  imm r0 4
  jmp radial_ready

radial_5:
  imm r0 5
  jmp radial_ready

radial_6_8:
  subi r0 abs_dx 2666
  jc r0 radial_8
  subi r0 abs_dx 2193
  jc r0 radial_7
  imm r0 6
  jmp radial_ready

radial_7:
  imm r0 7
  jmp radial_ready

radial_8:
  imm r0 8
  jmp radial_ready

radial_9_16:
  subi r0 abs_dx 5653
  jc r0 radial_13_16
  subi r0 abs_dx 4320
  jc r0 radial_11_12
  subi r0 abs_dx 3726
  jc r0 radial_10
  imm r0 9
  jmp radial_ready

radial_10:
  imm r0 10
  jmp radial_ready

radial_11_12:
  subi r0 abs_dx 4961
  jc r0 radial_12
  imm r0 11
  jmp radial_ready

radial_12:
  imm r0 12
  jmp radial_ready

radial_13_16:
  subi r0 abs_dx 7206
  jc r0 radial_15_16
  subi r0 abs_dx 6400
  jc r0 radial_14
  imm r0 13
  jmp radial_ready

radial_14:
  imm r0 14
  jmp radial_ready

radial_15_16:
  subi r0 abs_dx 8076
  jc r0 radial_16
  imm r0 15
  jmp radial_ready

radial_16:
  imm r0 16

radial_ready:
  add0 color
  add0 palette
  mov color r0

  ; color_index %= 11. The angular sector, ring, and phase sum is 0..65.
  subi r0 color 32
  jc r0 color_reduce_33_65
  subi r0 color 21
  jc r0 color_subtract_22
  subi r0 color 10
  jc r0 color_subtract_11
  jmp color_ready

color_reduce_33_65:
  subi0 11
  jc r0 color_reduce_44_65
  addi0 10
  mov color r0
  jmp color_ready

color_reduce_44_65:
  subi0 11
  jc r0 color_subtract_55
  addi0 10
  mov color r0
  jmp color_ready

color_subtract_55:
  subi0 1
  mov color r0
  jmp color_ready

color_subtract_22:
  subi0 1
  mov color r0
  jmp color_ready

color_subtract_11:
  subi0 1
  mov color r0

color_ready:
  ; Palette indices 0..8 map to C64 colors 2..10. The last two map to
  ; LightGreen (13) and LightBlue (14).
  addi color color 2
  subi r0 color 10
  jc r0 palette_high
  jmp emit

palette_high:
  addi color color 2

emit:
  screen_data color

  inc dx
  dec pixels
  jc pixels pixel

  inc dy
  dec rows
  jc rows row

  imm r0 0
  screen_swap r0

  ; Rotate the moving center by -1 degree.
  muli abs_dx sine 999848
  muli abs_dy cosine 17452
  sub r0 abs_dx abs_dy
  divi0 1000000
  mov abs_dx r0

  muli abs_dy cosine 999848
  muli temp sine 17452
  add r0 abs_dy temp
  divi0 1000000
  mov abs_dy r0

  mov sine abs_dx
  mov cosine abs_dy

  ; The source advances its palette by -1 every five frames.
  dec palette_ticks
  jc palette_ticks frame
  imm palette_ticks 5
  dec palette
  addi r0 palette 1
  jc r0 frame
  imm palette 10
  jmp frame
