.screen 64 64

; Rotating, breathing polar grid.
;
; atan2 is approximated by a 40-sector diamond angle:
;   quarter_angle = 10 * abs(dy) / (abs(dx) + abs(dy))
; Distance is approximated by max(abs(dx), abs(dy)) +
; 3/8 * min(abs(dx), abs(dy)). Radial boundaries retain the source's
; 3.0 initial spacing and 1.08 exponential growth.
;
; r2: center oscillator sine, scale 1,000,000
; r3: center oscillator cosine, scale 1,000,000
; r4: moving center x
; r5: moving center y
; r6: palette phase
; r7: palette phase frame counter
; r8: signed pixel x delta
; r9: signed pixel y delta
; r10: rows left
; r11: pixels left
; r12: absolute pixel x delta/radial state
; r13: absolute pixel y delta
; r14: angular sector/color
; r15: temporary
; r16: y delta is nonnegative

start:
  imm r2 0
  imm r3 1000000
  imm r6 0
  imm r7 5

frame:
  ; rr = 25 + 5*cos(frame), with the source's negative frame direction.
  muli r0 r3 5
  divi0 1000000
  addi0 25
  mov r15 r0

  ; center_x = 32 + rr*cos(frame)
  mul r0 r15 r3
  divi0 1000000
  addi0 32
  mov r4 r0

  ; center_y = 32 + rr*sin(frame)
  mul r0 r15 r2
  divi0 1000000
  addi0 32
  mov r5 r0

  imm r0 0
  sub0 r5
  mov r9 r0
  imm r10 64

row:
  imm r0 0
  sub0 r4
  mov r8 r0
  mov r13 r9
  addi r0 r13 1
  jc r0 dy_nonnegative
  neg r13
  imm r16 0
  jmp dy_ready

dy_nonnegative:
  imm r16 1

dy_ready:
  imm r11 64

pixel:
  mov r12 r8

  ; Split by quadrant while converting both deltas to absolute values.
  jc r12 dx_positive

  ; dx <= 0. Both sides agree on the y axis; handle the exact center here.
  neg r12
  add r15 r12 r13
  jc r15 dx_nonpositive_noncenter
  imm r14 0
  jmp angle_ready

dx_nonpositive_noncenter:
  jc r16 quadrant_2

  ; Quadrant 3: sector = 20 + q.
  muli r14 r13 10
  div r0 r14 r15
  addi0 20
  mov r14 r0
  jmp angle_ready

quadrant_2:
  ; Quadrant 2: sector = 20 - q.
  muli r14 r13 10
  div r14 r14 r15
  imm r15 20
  sub r14 r15 r14
  jmp angle_ready

dx_positive:
  jc r16 quadrant_1

  ; Quadrant 4: sector = 40 - q, with the positive x axis mapped to zero.
  muli r14 r13 10
  add r15 r12 r13
  div r14 r14 r15
  jc r14 quadrant_4_nonzero
  imm r14 0
  jmp angle_ready

quadrant_4_nonzero:
  imm r15 40
  sub r14 r15 r14
  jmp angle_ready

quadrant_1:
  ; Quadrant 1: sector = q. The denominator is positive because dx > 0.
  add r15 r12 r13
  muli r0 r13 10
  div0 r15
  mov r14 r0

angle_ready:
  ; Approximate hypot(dx,dy) and scale it by 100 for radial boundaries.
  sub r15 r12 r13
  jc r15 dx_is_larger

  ; dy >= dx
  muli r0 r12 3
  divi0 8
  mov r15 r0
  add r12 r13 r15
  jmp distance_ready

dx_is_larger:
  muli r0 r13 3
  divi0 8
  mov r15 r0
  add r12 r12 r15

distance_ready:
  muli r12 r12 100

  ; Classify the approximate distance through the exact cumulative ring
  ; thresholds generated by spacing = floor(spacing * 1.08).
  subi r0 r12 3176
  jc r0 radial_9_16
  subi r0 r12 973
  jc r0 radial_4_8
  subi r0 r12 300
  jc r0 radial_2_3
  subi r0 r12 0
  jc r0 radial_1
  imm r0 0
  jmp radial_ready

radial_1:
  imm r0 1
  jmp radial_ready

radial_2_3:
  subi r0 r12 624
  jc r0 radial_3
  imm r0 2
  jmp radial_ready

radial_3:
  imm r0 3
  jmp radial_ready

radial_4_8:
  subi r0 r12 1755
  jc r0 radial_6_8
  subi r0 r12 1349
  jc r0 radial_5
  imm r0 4
  jmp radial_ready

radial_5:
  imm r0 5
  jmp radial_ready

radial_6_8:
  subi r0 r12 2666
  jc r0 radial_8
  subi r0 r12 2193
  jc r0 radial_7
  imm r0 6
  jmp radial_ready

radial_7:
  imm r0 7
  jmp radial_ready

radial_8:
  imm r0 8
  jmp radial_ready

radial_9_16:
  subi r0 r12 5653
  jc r0 radial_13_16
  subi r0 r12 4320
  jc r0 radial_11_12
  subi r0 r12 3726
  jc r0 radial_10
  imm r0 9
  jmp radial_ready

radial_10:
  imm r0 10
  jmp radial_ready

radial_11_12:
  subi r0 r12 4961
  jc r0 radial_12
  imm r0 11
  jmp radial_ready

radial_12:
  imm r0 12
  jmp radial_ready

radial_13_16:
  subi r0 r12 7206
  jc r0 radial_15_16
  subi r0 r12 6400
  jc r0 radial_14
  imm r0 13
  jmp radial_ready

radial_14:
  imm r0 14
  jmp radial_ready

radial_15_16:
  subi r0 r12 8076
  jc r0 radial_16
  imm r0 15
  jmp radial_ready

radial_16:
  imm r0 16

radial_ready:
  add0 r14
  add0 r6
  mov r14 r0

  ; color_index %= 11. The angular sector, ring, and phase sum is 0..65.
  subi r0 r14 32
  jc r0 color_reduce_33_65
  subi r0 r14 21
  jc r0 color_subtract_22
  subi r0 r14 10
  jc r0 color_subtract_11
  jmp color_ready

color_reduce_33_65:
  subi0 11
  jc r0 color_reduce_44_65
  addi0 10
  mov r14 r0
  jmp color_ready

color_reduce_44_65:
  subi0 11
  jc r0 color_subtract_55
  addi0 10
  mov r14 r0
  jmp color_ready

color_subtract_55:
  subi0 1
  mov r14 r0
  jmp color_ready

color_subtract_22:
  subi0 1
  mov r14 r0
  jmp color_ready

color_subtract_11:
  subi0 1
  mov r14 r0

color_ready:
  ; Palette indices 0..8 map to C64 colors 2..10. The last two map to
  ; LightGreen (13) and LightBlue (14).
  addi r14 r14 2
  subi r0 r14 10
  jc r0 palette_high
  jmp emit

palette_high:
  addi r14 r14 2

emit:
  screen_data r14

  inc r8
  dec r11
  jc r11 pixel

  inc r9
  dec r10
  jc r10 row

  imm r0 0
  screen_swap r0

  ; Rotate the moving center by -1 degree.
  muli r12 r2 999848
  muli r13 r3 17452
  sub r0 r12 r13
  divi0 1000000
  mov r12 r0

  muli r13 r3 999848
  muli r15 r2 17452
  add r0 r13 r15
  divi0 1000000
  mov r13 r0

  mov r2 r12
  mov r3 r13

  ; The source advances its palette by -1 every five frames.
  dec r7
  jc r7 frame
  imm r7 5
  dec r6
  addi r0 r6 1
  jc r0 frame
  imm r6 10
  jmp frame
